name: build

on: workflow_dispatch

jobs:

  build:
    name: build

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-22.04', 'macos-10.15', 'windows-latest']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt --yes install qt6-base-dev libgl1-mesa-glx 
      - name: Install Python dependencies
        run: |
          pip install pdm
          pdm install
      - name: Run Pyinstaller
        run: |
          pdm run pyinstaller BeeRef.spec
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}
          path: dist/*
          retention-days: 5
